In [9]:
import numpy as np
import ipywidgets as widgets
from IPython.display import display
from IPython.display import clear_output
import matplotlib.pyplot as plt

# Функция активации
def f(x):
    if(x >= 0):
        return 1
    else:
        return 0
    
# Однослойная нейронная сеть
class Neuronet:
    def __init__(self,n,m,bias=True):
        self.n = n # Входы сети
        self.m = m # Выходы
        self.bias = bias # Использовать или нет веса смещения
        self.w = np.zeros((n,m)) # Веса сети
        self.w0 = np.zeros(m) # Веса смещения
    
    # Обучение сети
    def fit(self,X,y):
        maxiter = 1000 # Максимальное кол-во итераций
        err = 0 # Кол-во ошибок
        t = 0 # Кол-во итераций 
        while(True):
            err = 0 # Обнуляем каждую эпоху обучения
            # Цикл по всем векторам обучающего мн-ва
            for k in range(len(X)):
                y_out,z = np.zeros(self.m),np.zeros(self.m)
                
                # Прямое распространение
                for j in range(self.m):
                    for i in range(self.n):
                        z[j] += self.w[i][j]*X[k][i]
                    if(self.bias):
                        y_out[j] = f(z[j] + self.w0[j]) # Применяем функцию активации
                    else:
                        y_out[j] = f(z[j]) # Применяем функцию активации
                
                # Проверка совпадения
                for i in range(self.m):
                    if(y[k][i] != y_out[i]):
                        err += 1
                
                # Коррекция весов
                for i in range(self.n):
                    for j in range(self.m):
                        self.w[i][j] += X[k][i]*(y[k][j]-y_out[j])
                
                if(self.bias):
                    # Коррекция весов смещения
                    for i in range(self.m):
                        self.w0[i] += (y[k][i] - y_out[i]) # x = 1
            
            # Если все правильно распознано
            if(err == 0 or t > maxiter):
                print("Кол-во итераций обучения: " + str(t))
                break
            else:
                t += 1
    
    # Метод возвращает кол-во весов равных нулю в процентах
    def weight(self):
        c = 0
        for i in range(self.m):
            for j in range(self.n):
                if(self.w[j][i] == 0):
                    c += 1
            if(self.w0[i] == 0 and self.bias):
                c += 1
        k = self.n*self.m
        if(self.bias):
            k += self.m
        return c/k*100.0
    
    # Распознавание сети
    def predict(self,X):
        res = [] # Результаты
        for x in X:
            y_out = np.zeros(self.m)
            for j in range(self.m):
                for i in range(self.n):
                    y_out[j] += self.w[i][j]*x[i]
                if(self.bias):
                    y_out[j] = f(y_out[j] + self.w0[j])
                else:
                    y_out[j] = f(y_out[j])
            res.append(list(y_out))
        return res
    
# Мн-во ответов на входные образы
def generate(n):
    y = [np.zeros(n) for i in range(n)]
    for i in range(len(y)):
        y[i][i] = 1
    return y

In [10]:
M = '1 1 0 0 0 1 1\
     1 1 1 0 1 1 1\
     1 1 1 1 1 1 1\
     1 1 0 1 0 1 1\
     1 1 0 0 0 1 1\
     1 1 0 0 0 1 1'
M1 ='1 0 0 0 0 0 1\
     1 1 0 0 0 1 1\
     1 0 1 0 1 0 1\
     1 0 0 1 0 0 1\
     1 0 0 0 0 0 1\
     1 0 0 0 0 0 1'
M2 ='0 0 0 0 0 0 0\
     0 1 0 0 0 1 0\
     0 1 1 0 1 1 0\
     0 1 0 1 0 1 0\
     0 1 0 0 0 1 0\
     0 1 0 0 0 1 0'
D = '0 0 1 1 1 0 0\
     0 0 1 0 1 0 0\
     0 1 0 0 0 1 0\
     0 1 1 1 1 1 0\
     1 1 0 0 0 1 1\
     1 0 0 0 0 0 1'
D1 ='0 0 1 1 1 0 0\
     0 1 1 0 1 1 0\
     0 1 1 0 1 1 0\
     0 1 1 1 1 1 0\
     1 1 1 1 1 1 1\
     1 1 0 0 0 1 1'
D2 ='0 0 1 1 1 0 0\
     0 1 0 0 0 1 0\
     0 1 0 0 0 1 0\
     1 1 1 1 1 1 1\
     1 0 0 0 0 0 1\
     1 0 0 0 0 0 1'
A = '0 0 1 1 1 0 0\
     0 1 1 0 1 1 0\
     0 1 0 0 0 1 0\
     0 1 1 1 1 1 0\
     0 1 0 0 0 1 0\
     0 1 0 0 0 1 0'
A1 ='0 0 0 1 0 0 0\
     0 0 1 0 1 0 0\
     0 1 1 0 1 1 0\
     0 1 1 1 1 1 0\
     0 1 0 0 0 1 0\
     1 1 1 0 1 1 1'
A2 ='0 0 0 0 0 0 0\
     0 0 0 1 0 0 0\
     0 0 1 0 1 0 0\
     0 0 1 1 1 0 0\
     0 1 0 0 0 1 0\
     1 0 0 0 0 0 1'
N1 ='0 0 0 0 1 0 0\
     0 0 0 1 1 0 0\
     0 0 1 0 1 0 0\
     0 0 0 0 1 0 0\
     0 0 0 0 1 0 0\
     0 0 0 1 1 1 0'
N11='0 0 0 0 1 1 0\
     0 0 0 1 1 1 0\
     0 0 1 1 1 1 0\
     0 0 0 0 1 1 0\
     0 0 0 0 1 1 0\
     0 0 0 1 1 1 1'
N12='0 0 0 1 1 0 0\
     0 0 1 1 1 0 0\
     0 1 1 1 1 0 0\
     0 0 0 1 1 0 0\
     0 0 0 1 1 0 0\
     0 0 0 1 1 0 0'
N2 ='0 0 1 1 1 0 0\
     0 1 0 0 0 1 0\
     0 0 0 0 1 0 0\
     0 0 0 1 0 0 0\
     0 0 1 0 0 0 0\
     0 1 1 1 1 1 0'
N21 ='0 0 1 1 1 0 0\
     0 1 1 1 1 1 0\
     0 1 0 0 1 1 0\
     0 0 0 1 1 0 0\
     0 0 1 1 0 0 0\
     0 1 1 1 1 1 1'
N22 ='1 1 1 1 1 1 0\
     1 1 0 0 1 1 0\
     0 0 0 1 1 0 0\
     0 0 1 1 0 0 0\
     0 1 1 1 1 0 0\
     0 1 1 1 1 1 0'

trainx = widgets.Textarea(
    value='1 0 1 1 1 1 0 0 1\n1 1 1 1 0 1 1 0 1',
    placeholder='Ввод здесь',
    description='X train:',
    disabled=False,
    layout=widgets.Layout(width="650px",height="120px")
)

trainy = widgets.Textarea(
    value='1 0\n0 1',
    placeholder='Ввод здесь',
    description='Y train:',
    disabled=False,
    layout=widgets.Layout(width="650px",height="120px")
)

testx = widgets.Textarea(
    value='1 0 1 1 1 1 1 0 1',
    placeholder='Ввод здесь',
    description='X test',
    disabled=False,
    layout=widgets.Layout(width="650px",height="120px")
)

# Тест на эталонных образцах
box = widgets.Checkbox(False)

# Тест на различных образах
box1 = widgets.Checkbox(False)

# Вкл нейроны смещения
bias = widgets.Checkbox(True)

# Для упрощения
def menu():
    print('Для ввода обучающих образов X:')
    display(trainx)
    print('Для ввода ответов Y:')
    display(trainy)
    print('Для ввода тестируюшего мн-ва X:')
    display(testx)
    print('Протестировать сеть на одиночных образах для каждого класса:')
    display(box)
    print('Протестировать сеть на различных образах для каждого класса:')
    display(box1)
    print('Учет нейрона смещения')
    display(bias)
    display(start)

# Разбор строки
def getdata(s):
    mas = s.split(' ')
    l = []
    for i in mas:
        if(i.isdigit()):
            l.append(int(i))
    return l

# Метод для применения изменений
def on_change(btn):
    clear_output()
    menu()
    x,y = [],[]
    if(box.value and box1.value):
        print('Выберите что-то одно!')
        return
    if(box.value):
        for i in [M,D,A,N1,N2]:
            x.append(getdata(i))
        y = generate(len(x))
    elif(box1.value):
        for i in [M,M1,M2,D,D1,D2,A,A1,A2,N1,N11,N12,N2,N21,N22]:
            x.append(getdata(i))
        for i in range(5):
            for j in range(3):
                s = np.zeros(5)
                s[i] = 1
                y.append(s)
    else:
        # Парсим данные со страницы
        r = trainx.value.split('\n')
        for i in r:
            x.append(getdata(i))
        r = trainy.value.split('\n')
        for i in r:
            y.append(getdata(i))
    # Для прогноза берем данные из последнего текстового окна на странице
    pred = []
    r = testx.value.split('\n')
    for i in r:
        pred.append(getdata(i))
    print('Результаты:\n')
    net = Neuronet(len(x[0]),len(y[0]),bias.value) # Создаем объект
    net.fit(x,y) # Обучаем сеть
    print("\nПроцент неактивных весов: " + str(round(net.weight(),2)) + "%")
    print('\nМатрица весов W:')
    for i in range(0,len(x[0]),3):
        print(net.w[i],net.w[i+1],net.w[i+2])
    if(bias.value):
        print(net.w0)
    print("\nПрогноз:")
    if(len(pred[0]) != len(x[0])):
        print('Ошибка в размерности входного мн-ва!')
    else:
        y_pred = net.predict(pred)
        for i in y_pred:
            print(i)
    
# Кнопка для применения изменений
start = widgets.Button(description='Запустить')
menu()
start.on_click(on_change)

Для ввода обучающих образов X:


Textarea(value='1 0 1 1 1 1 0 0 1\n1 1 1 1 0 1 1 0 1', description='X train:', layout=Layout(height='120px', width='650px'), placeholder='Ввод здесь')

Для ввода ответов Y:


Textarea(value='1 0\n0 1', description='Y train:', layout=Layout(height='120px', width='650px'), placeholder='Ввод здесь')

Для ввода тестируюшего мн-ва X:


Textarea(value='0 0 1 1 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 0\n0 0 1 1 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 1 0\n0 0 1 0 1 0 1 1 1 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 0', description='X test', layout=Layout(height='120px', width='650px'), placeholder='Ввод здесь')

Протестировать сеть на одиночных образах для каждого класса:


Checkbox(value=False)

Протестировать сеть на различных образах для каждого класса:


Checkbox(value=True)

Учет нейрона смещения


Checkbox(value=False)

Button(description='Запустить', style=ButtonStyle())

Результаты:

Кол-во итераций обучения: 6

Процент неактивных весов: 18.57%

Матрица весов W:
[ 1. -2. -1. -1. -1.] [ 1. -1. -1. -1. -1.] [-3.  2.  0. -1.  2.]
[-3.  0.  1. -1.  2.] [-4.  1. -2.  1.  0.] [ 0. -1. -1.  0. -1.]
[ 2. -2. -1. -1. -1.] [ 1. -2. -1. -1. -1.] [ 1. -3.  0. -2.  1.]
[ 0. -1.  1. -1.  0.] [-1. -2. -1.  1.  0.] [-2. -1.  0.  1. -2.]
[ 0. -3.  0. -1.  1.] [ 2. -2. -1. -1. -1.] [ 2. -2. -1. -1. -1.]
[ 1. -1. -2. -1.  0.] [ 1. -1. -2.  0. -4.] [ 0. -2. -2.  0. -1.]
[ 0. -1. -4. -1. -1.] [ 0.  0. -1.  0.  0.] [ 2. -2. -1. -1. -1.]
[ 2. -2. -1. -1. -1.] [ 1.  0.  0. -1. -2.] [-3.  0.  6. -1. -1.]
[ 0. -3. -1. -3.  1.] [-3. -1.  3.  1. -1.] [ 0.  0.  0.  0. -2.]
[ 2. -2. -1. -1. -1.] [ 0.  5. -5. -1. -2.] [ 0. -1.  2. -2. -2.]
[-2.  4. -2. -1.  2.] [-2.  3. -2.  0.  1.] [-3.  3. -2.  2. -3.]
[ 0. -1.  2. -1. -2.] [ 0.  5. -5. -1. -2.] [ 0.  3. -1. -2. -2.]
[ 1. -3.  2. -2.  1.] [-1. -1.  0. -1.  3.] [-2. -1. -4.  1.  1.]
[-2. -2. -2.  1.  1.] [ 0. -3.  1.  0. -1.] [-1. 